name: Build APK Kivy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Linux Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config
          sudo apt install -y zlib1g-dev libncurses5-dev libncursesw5-dev
          sudo apt install -y libtinfo5 cmake libffi-dev libssl-dev
          sudo apt install -y build-essential ccache

      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36
          pip install buildozer

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android Packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.2"
          sdkmanager "ndk;25.2.9519653"

      - name: Set Android SDK Path
        run: |
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROIDSDK=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/local/lib/android/sdk/build-tools/33.0.2" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RekapVoucher-APK
          path: bin/*.apk
