name: Build APK Kivy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk
          sudo apt install -y python3-pip autoconf libtool pkg-config
          sudo apt install -y zlib1g-dev libncurses5-dev libncursesw5-dev
          sudo apt install -y libtinfo5 cmake libffi-dev libssl-dev

      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RekapVoucher-APK
          path: bin/*.apk
