name: Build APK Kivy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk
          sudo apt install -y autoconf libtool pkg-config zlib1g-dev
          sudo apt install -y libncurses5-dev libncursesw5-dev
          sudo apt install -y libtinfo5 cmake libffi-dev libssl-dev
          sudo apt install -y build-essential ccache

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36
          pip install buildozer

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Install Android Build Tools
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.2"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RekapVoucher-APK
          path: bin/*.apk
